{{- if .Values.rbac.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "nodetaint.fullname" . }}
  labels:
    {{- include "nodetaint.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - nodes
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - extensions
  resources:
    - daemonsets
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - apps
  resources:
    - daemonsets
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
    - watch
{{- end -}}
